packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!apps/nextjs'
  - '!packages/workflow'
  - '!packages/chatbot'

catalog:
  "@tanstack/react-query": ^5.64.1
  "@trpc/client": ^11.0.0-rc.700
  "@trpc/react-query": ^11.0.0-rc.700
  "@trpc/server": ^11.0.0-rc.700
  eslint: ^9.18.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  # The version of `zod` should be the same across all packages and dependencies.
  # Otherwise, you may get the following error:
  #   Type instantiation is excessively deep and possibly infinite
  zod: ^3.24.2
  ai: ^4.1.44

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
